### ISSUE TITLE
Grafana config is not properly persistent

### ISSUE THREAD

**Issue by MatthewCroughan** [DynamicDevices/ming#14]
For some reason all of its data isn't stored in /data, just noting this down so I can fix it later.

**Comment by MatthewCroughan** [comment]
The reason for this is that `/var/lib/grafana/grafana.db` container *everything* relating to Grafana, so the application is inherently stateful. This includes dashboards, database configuration and more. We can only set this up during the first runtime, anything included in /etc/provisioning at runtime will be built into grafana.db, but this would require us *every single time* we build the container to make sure we have backed up our dashboards and put these dashboards into /etc/provisioning.

We already automate the provisioning of the intercontainer influxdb connection like so:

```dockerfile
COPY ./datasources/datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
```

where the contents of datasources.yaml are as follows:

```yml
 lines (12 sloc) 233 Bytes
apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: ming_default
    user: admin
    url: http://influxdb:8086
    jsonData:
      timeInterval: "15s"
    secureJsonData:
      password:
```
